### ISSUE TITLE
freenect2_DIR-NOTFOUND

### ISSUE THREAD

**Issue by jiaojialulu** [sugar10w/kinect_tasks#1]
请问我下了libfreenect2并且当中的protonect.exe也可以运行。因此我想试一下您的程序，但是cmake的时候显示freenect2_DIR-NOTFOUND，这里应该如何修改呢？
刚做kinect，请尽快回复，谢谢帮助！

**Comment by sugar10w** [comment]
Protonect.exe ...  您是在Windows下测试的么? 我是在Ubuntu14.04下测试我的代码的。在编译安装libfreenect2的时候，sudo make install 就安装到默认路径了
没有在Windows下测试过libfreenect2，所以很抱歉我不太懂....

**Comment by jiaojialulu** [comment]
没关系，还是谢谢哈！
